# <b> chi-squared test卡方检验 </b>

　　卡方检验：是一种用途很广的计数资料的假设检验方法。它属于非参数检验的范畴，主要是比较两个及两个以上样本率( 构成比）以及两个分类变量的关联性分析。其根本思想就是在于比较理论频数和实际频数的吻合程度或拟合优度问题。

　　它在分类资料统计推断中的应用，包括：两个率或两个构成比比较的卡方检验；多个率或多个构成比比较的卡方检验以及分类资料的相关分析等。
  
  样本量要求：80%以上的频数必须大于5，所有频数必须大于1）。

H0：观察频数与期望频数没有差别     H1 ： 观察频数与期望频数有差别

如果P值很小，说明观察值与理论值偏离程度太大，应当拒绝无效假设，表示比较资料之间有显著差异；否则就不能拒绝无效假设，尚不能认为样本所代表的实际情况和理论假设有差别。

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

cols = ['A', 'B', 'C', 'D']
data = pd.DataFrame(columns=cols)

data.loc['White Collar'] = [90, 60, 104, 95]
data.loc['Blue Collar'] = [30, 50, 51, 20]
data.loc['No collar'] = [30, 40, 45, 35]

print (data)

               A   B    C   D
White Collar  90  60  104  95
Blue Collar   30  50   51  20
No collar     30  40   45  35


In [2]:
V, p, dof, expected = stats.chi2_contingency(data) 
# add correction=False for uncorrected Chi-square

print ('P value for effect of area on proportion of each collar:')
print (p)
print ('\nExpected numbers if area did not effect proportion of each collar:')
print (expected)


P value for effect of area on proportion of each collar:
0.0004098425861096696

Expected numbers if area did not effect proportion of each collar:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


# <b>  Fisher'exact test Fisher 确切检验</b>
和卡方检验类似，但Fish更适合用于小样本数据集，即20%的频数小于5或至少一个频数等于0的情况下

In [5]:

obs = np.array([[1,5], [8,2]])
fisher_result = stats.fisher_exact(obs)

p_val = fisher_result[1]

print ('Data:')
print (obs)

print ('\nProbability that column does not effect row values:')
print (p_val)

Data:
[[1 5]
 [8 2]]

Probability that column does not effect row values:
0.03496503496503495
