<b> 参考网址 ： https://wenku.baidu.com/view/dac85a6e3868011ca300a6c30c2259010302f304.html </b> 



<center><img src='data/corr.jpg' /> </center>


## <b> 数据集相关度系数简介  </b> ##

df ：pandas 数据框（dataframe）

df.corr() #计算pearson相关系数

df.corr('spearman')  #计算spearman相关系数

df.corr('kendall')  #计算kendall相关系数

# 1. 连续变量的相关分析

　　虽然样本相关系数r可作为总体相关系数ρ的估计值，但从相关系数ρ=0的总体中抽出的样本，计算其相关系数r，因为有抽样误差，故不一定是0，要判断不等于0的r值是来自ρ=0的总体还是来自ρ≠0的总体，必须进行显著性检验。检验假设是ρ=0，r与0的差别是否显著要按该样本来自ρ=0的总体概率而定。如果从相关系数ρ=0的总体中取得某r值的概率P>0.05，我们就接受假设，认为此r值的很可能是从此总体中取得的。因此判断两变量间无显著关系；如果取得r值的概率P≤0.05或P≤0.01，我们就在α=0.05或α=0.01水准上拒绝检验假设，认为该r值不是来自ρ=0的总体，而是来自ρ≠0的另一个总体，因此就判断两变量间有显著关系。

In [3]:
import os
import pandas as pd
import seaborn as sns
import numpy as np
import scipy
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
import statsmodels.stats.proportion as smp
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

dir = "./"
print(os.listdir("./"))  # 确认路径正确

['.ipynb_checkpoints', 'data', 'install.ipynb', '10. ROC分析.ipynb', '02 . 统计描述.ipynb', '01. 绪论.ipynb', '04. 两组数值变量比较的假设检验.ipynb', '05. 多组数值变量比较的假设检验.ipynb', '06. 有序变量比较的假设检验.ipynb', '09. 逻辑回归分析.ipynb', '07. 分类变量比较的假设检验.ipynb', '08. 相关性假设检验.ipynb', '03. 常规检验.ipynb']


In [4]:
df = pd.read_csv(dir+"data/心脏病诊断数据集（原数据）.csv",header=None) #读取csv文件，没有列名
df.columns = ["年龄","性别","胸痛类型","静息血压","血浆类固醇含量（mg/dl）","空腹血糖>120mg/dl","静息心电图结果","最高心率","运动型心绞痛","运动引起的ST下降","最大运动量时心电图ST的斜率","使用荧光染色法测定的主血管数","THAL","患病情况"]                                                 #添加列名
df.head(5)

年龄  性别  胸痛类型  静息血压  血浆类固醇含量（mg/dl）  空腹血糖>120mg/dl  静息心电图结果  最高心率  运动型心绞痛  \
0  70   1     4   130             322              0        2   109       0   
1  67   0     3   115             564              0        2   160       0   
2  57   1     2   124             261              0        0   141       0   
3  64   1     4   128             263              0        0   105       1   
4  74   0     2   120             269              0        2   121       1   

   运动引起的ST下降  最大运动量时心电图ST的斜率  使用荧光染色法测定的主血管数  THAL  患病情况  
0        2.4               2               3     3     2  
1        1.6               2               0     7     1  
2        0.3               1               0     7     2  
3        0.2               2               1     7     1  
4        0.2               1               1     3     1

# <b>Pearson相关性分析</b>

<b>Pearson:皮尔森相关性系数,约束条件：</b>

1、两个变量间有线性关系,如果是曲线相关可能不准确。

2、变量是连续变量

3、两个变量的总体均符合正态分布：取大样本进行正态分布非参数检验

4、两变量独立
  
  由于来自ρ-0的总体的所有样本相关系数呈对称分布，故r的显著性可用t检验来进行。进行t检验的步骤为：
  
  1．提出假设，H0：ρ=0，H1：ρ≠0，α=0.01
  
  2．计算相关系数的r的t值、 p值


In [5]:
r , p = stats.pearsonr(df["性别"],df["静息血压"])
print("Pearson相关系数 :",r,"\nT检验P_value :",p)   

Pearson相关系数 -0.06269339383516666 
T检验P_value : 0.30470865932721747


# Spearman相关性检验

spearman: 斯皮尔曼相关性系数，通常也叫斯皮尔曼秩相关系数,属于非参数统计方法。。“秩”，可以理解成就是一种顺序或者排序，那么它就是根据原始数据的排序位置进行求解，这种表征形式就没有了求皮尔森相关性系数时那些限制。

<b> 适用条件 </b>

    不服从双变量正态分布；

    总体分布形态未知；

    原始数据是等级资料。    

符合其中任何一条，即可采用spearman相关性分析。

<b> 分析步骤 </b>    

    提出假设 , H0 : X 和 Y 不相关 ， H1 ： X 和 Y 相关

<center><img src='data/spearman.jpg' /> </center>

In [6]:
sp , p = stats.spearmanr(df["性别"],df["静息血压"])
print("Spearman相关系数 :",sp,"\nT检验P_value :",p)  

Spearman相关系数 -0.054963048307219806 
T检验P_value : 0.3683197623845299


# 2. 有序分类变量的相关性分析

有序分类变量的相关性又称为一致性，即行变量等级高的列变量等级也高，如果行变量等级高而列变量等级低，则称为不一致。

常用的统计量有：Gamma、Kendall的tau-b、Kendall的tau-c等。

kendall ： 肯德尔相关系数是以Maurice Kendall命名的，并经常用希腊字母τ（tau）表示其值。肯德尔相关系数是一个用来测量两个随机变量相关性的统计值。一个肯德尔检验是一个无参数假设检验，它使用计算而得的相关系数去检验两个随机变量的统计依赖性。肯德尔相关系数的取值范围在-1到1之间，当τ为1时，表示两个随机变量拥有一致的等级相关性；当τ为-1时，表示两个随机变量拥有完全相反的等级相关性；当τ为0时，表示两个随机变量是相互独立的。


In [13]:
tau , p  = stats.kendalltau(df["静息心电图结果"] , df["最大运动量时心电图ST的斜率"])
print ("统计值 ： " , tau )
print("p值 ：  " , p )

统计值 ：  0.15698430306305192
p值 ：   0.007960500725717105


# 3. 无序分类变量的相关分析

最常用的为卡方检验(在“分类变量比较的假设检验”章节有此检验方法的介绍），用于评价两个无序分类变量的相关性。根据卡方值衍生出来的指标还有列联系数、Phi、Cramer的V、Lambda系数、不确定系数等。

OR、RR也是衡量两变量之间的相关程度的指标。

In [14]:
cols = ['A', 'B', 'C', 'D']
data = pd.DataFrame(columns=cols)

data.loc['White Collar'] = [90, 60, 104, 95]
data.loc['Blue Collar'] = [30, 50, 51, 20]
data.loc['No collar'] = [30, 40, 45, 35]

print (data)

               A   B    C   D
White Collar  90  60  104  95
Blue Collar   30  50   51  20
No collar     30  40   45  35


In [15]:
V, p, dof, expected = stats.chi2_contingency(data) 
# add correction=False for uncorrected Chi-square

print ('P value for effect of area on proportion of each collar:')
print (p)
print ('\nExpected numbers if area did not effect proportion of each collar:')
print (expected)

P value for effect of area on proportion of each collar:
0.0004098425861096696

Expected numbers if area did not effect proportion of each collar:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]
